/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include "AS3/AS3.h"
#define swig_as3(X) inline_as3("import com.adobe.flascc.swig.*; " X)


/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) {int msglen = strlen(msg);__asm__ volatile ("throw new Exception(CModule.readString(%0, %1))": : "r"(msg), "r"(msglen));}



#include <string.h>
#include "aes.h"

__attribute__((annotate("as3sig:public function _wrap_AesCtx_Ek_set(self, Ek:int):void")))
void _wrap_AesCtx_Ek_set() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned int *arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, Ek);
  }
  {
    size_t ii;
    unsigned int *b = (unsigned int *) arg1->Ek;
    for (ii = 0; ii < (size_t)60; ii++) b[ii] = *((unsigned int *) arg2 + ii);
  }
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesCtx_Ek_get(self):int")))
void _wrap_AesCtx_Ek_get() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned int *result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (unsigned int *)(unsigned int *) ((arg1)->Ek);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesCtx_Dk_set(self, Dk:int):void")))
void _wrap_AesCtx_Dk_set() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned int *arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, Dk);
  }
  {
    size_t ii;
    unsigned int *b = (unsigned int *) arg1->Dk;
    for (ii = 0; ii < (size_t)60; ii++) b[ii] = *((unsigned int *) arg2 + ii);
  }
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesCtx_Dk_get(self):int")))
void _wrap_AesCtx_Dk_get() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned int *result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (unsigned int *)(unsigned int *) ((arg1)->Dk);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesCtx_Iv_set(self, Iv:int):void")))
void _wrap_AesCtx_Iv_set() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned int *arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    AS3_GetScalarFromVar(arg2, Iv);
  }
  {
    size_t ii;
    unsigned int *b = (unsigned int *) arg1->Iv;
    for (ii = 0; ii < (size_t)4; ii++) b[ii] = *((unsigned int *) arg2 + ii);
  }
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesCtx_Iv_get(self):int")))
void _wrap_AesCtx_Iv_get() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned int *result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (unsigned int *)(unsigned int *) ((arg1)->Iv);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesCtx_Nr_set(self, Nr:String):void")))
void _wrap_AesCtx_Nr_set() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned char arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    inline_nonreentrant_as3(
      "%0 = Nr.charCodeAt(0)" : "=r"(arg2)
      );
  }
  if (arg1) (arg1)->Nr = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesCtx_Nr_get(self):String")))
void _wrap_AesCtx_Nr_get() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned char result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (unsigned char) ((arg1)->Nr);
  {
    AS3_DeclareVar(asresult, String);
    AS3_CopyCStringToVar(asresult, &result, 1);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesCtx_Mode_set(self, Mode:String):void")))
void _wrap_AesCtx_Mode_set() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned char arg2 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  {
    inline_nonreentrant_as3(
      "%0 = Mode.charCodeAt(0)" : "=r"(arg2)
      );
  }
  if (arg1) (arg1)->Mode = arg2;
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesCtx_Mode_get(self):String")))
void _wrap_AesCtx_Mode_get() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned char result ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  result = (unsigned char) ((arg1)->Mode);
  {
    AS3_DeclareVar(asresult, String);
    AS3_CopyCStringToVar(asresult, &result, 1);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_new_AesCtx():int")))
void _wrap_new_AesCtx() {
  AesCtx *result ;
  
  result = (AesCtx *)calloc(1, sizeof(AesCtx));
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_delete_AesCtx(self):void")))
void _wrap_delete_AesCtx() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  
  {
    AS3_GetScalarFromVar(arg1, self);
  }
  free((char *) arg1);
  {
    
  }
  {
    AS3_ReturnAS3Var(undefined);
  }
}


__attribute__((annotate("as3sig:public function _wrap_KEY128():int")))
void _wrap_KEY128() {
  int result ;
  
  result = 16;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_KEY192():int")))
void _wrap_KEY192() {
  int result ;
  
  result = 24;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_KEY256():int")))
void _wrap_KEY256() {
  int result ;
  
  result = 32;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_BLOCKSZ():int")))
void _wrap_BLOCKSZ() {
  int result ;
  
  result = 16;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_EBC():int")))
void _wrap_EBC() {
  int result ;
  
  result = 0;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_CBC():int")))
void _wrap_CBC() {
  int result ;
  
  result = 1;
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesCtxIni(pCtx:int, ivPointer:int, keyPointer:int, KeyLen:int, Mode:String):int")))
void _wrap_AesCtxIni() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  unsigned char arg5 ;
  int result ;
  
  {
    AS3_GetScalarFromVar(arg1, pCtx);
  }
  {
    AS3_GetScalarFromVar(arg2, ivPointer);
  }
  {
    AS3_GetScalarFromVar(arg3, keyPointer);
  }
  {
    AS3_GetScalarFromVar(arg4, KeyLen);
  }
  {
    inline_nonreentrant_as3(
      "%0 = Mode.charCodeAt(0)" : "=r"(arg5)
      );
  }
  result = (int)AesCtxIni(arg1,arg2,arg3,arg4,arg5);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


__attribute__((annotate("as3sig:public function _wrap_AesDecrypt(pCtx:int, cipher:int, data:int, CipherLen:int):int")))
void _wrap_AesDecrypt() {
  AesCtx *arg1 = (AesCtx *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  unsigned int arg4 ;
  int result ;
  
  {
    AS3_GetScalarFromVar(arg1, pCtx);
  }
  {
    AS3_GetScalarFromVar(arg2, cipher);
  }
  {
    AS3_GetScalarFromVar(arg3, data);
  }
  {
    AS3_GetScalarFromVar(arg4, CipherLen);
  }
  result = (int)AesDecrypt(arg1,arg2,arg3,arg4);
  {
    AS3_DeclareVar(asresult, int);
    AS3_CopyScalarToVar(asresult, result);
  }
  {
    AS3_ReturnAS3Var(asresult);
  }
}


